package com.becalm.android.data.local.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import com.becalm.android.data.local.db.entity.RawIngestionEventEntity
import kotlinx.coroutines.flow.Flow
import kotlinx.datetime.Instant

/**
 * Room DAO for [RawIngestionEventEntity].
 *
 * All queries that return data once are `suspend` functions executed on Room's
 * internal dispatcher. Observable queries return [Flow] and are collected by
 * the repository layer on the appropriate coroutine scope.
 *
 * Index usage is noted per query to aid future query-plan debugging:
 * - `idx_raw_events_user_sync`      → (user_id, sync_status)
 * - `idx_raw_events_user_time`      → (user_id, timestamp)
 * - `idx_raw_events_user_person_time` → (user_id, person_ref, timestamp)
 */
@Dao
public interface RawIngestionEventDao {

    /**
     * Inserts a single event. Uses [OnConflictStrategy.IGNORE] so that a duplicate
     * [RawIngestionEventEntity.clientEventId] (same idempotency key) is silently
     * dropped rather than throwing. The caller should check the returned row ID;
     * `-1L` means the row was ignored.
     *
     * @return The new row ID, or `-1L` if the row was ignored due to a conflict.
     */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    public suspend fun insert(entity: RawIngestionEventEntity): Long

    /**
     * Inserts a batch of events in a single transaction. Each item uses
     * [OnConflictStrategy.IGNORE] for the same idempotency guarantee as [insert].
     *
     * @return A list of row IDs parallel to [entities]; `-1L` at position N means
     *   the Nth entity was ignored due to a conflict.
     */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    public suspend fun insertAll(entities: List<RawIngestionEventEntity>): List<Long>

    /**
     * Replaces all columns of an existing row matched by primary key [RawIngestionEventEntity.id].
     *
     * @return The number of rows updated (0 if no matching row exists, 1 on success).
     */
    @Update
    public suspend fun update(entity: RawIngestionEventEntity): Int

    /**
     * Looks up an event by its client-generated idempotency key before inserting,
     * allowing callers to skip re-insertion entirely rather than relying solely on
     * the DB conflict strategy.
     *
     * Uses index: `idx_raw_events_user_sync` partial scan (user_id prefix) — full
     * coverage requires a composite index on (user_id, client_event_id), but the
     * idempotency check is low-frequency so the existing user_id index is sufficient.
     *
     * @param userId The Supabase auth.users UUID of the owning user.
     * @param clientEventId The UUID v4 idempotency key generated by the client.
     * @return The matching entity, or null if it does not yet exist locally.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND client_event_id = :clientEventId
        LIMIT 1
        """,
    )
    public suspend fun findByClientEventId(
        userId: String,
        clientEventId: String,
    ): RawIngestionEventEntity?

    /**
     * Returns up to [limit] events for [userId] whose [RawIngestionEventEntity.syncStatus]
     * is "pending", ordered oldest-first so that the sync worker uploads in ingestion order.
     *
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status) for the WHERE
     * predicate, then `idx_raw_events_user_time` (user_id, timestamp) for ORDER BY.
     *
     * @param userId The Supabase auth.users UUID.
     * @param limit Maximum number of rows to return (aligned to batch upload cap of 100).
     * @return List of pending entities, oldest timestamp first.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND sync_status = 'pending'
        ORDER BY timestamp ASC
        LIMIT :limit
        """,
    )
    public suspend fun findPendingForUpload(
        userId: String,
        limit: Int,
    ): List<RawIngestionEventEntity>

    /**
     * Marks a set of events as successfully synced by setting their
     * [RawIngestionEventEntity.syncStatus] to "synced" in a single UPDATE.
     *
     * Called by the sync worker after a successful Railway batch acknowledgement.
     * Room's `IN (:ids)` binding expands the list at compile time.
     *
     * @param ids List of [RawIngestionEventEntity.id] values to mark synced.
     */
    @Query(
        """
        UPDATE raw_ingestion_events
        SET sync_status = 'synced'
        WHERE id IN (:ids)
        """,
    )
    public suspend fun markSynced(ids: List<String>)

    /**
     * Records a failed upload attempt for a single event. Sets
     * [RawIngestionEventEntity.syncStatus] to "failed", increments
     * [RawIngestionEventEntity.retryCount] by [retryIncrement], and records
     * [now] as [RawIngestionEventEntity.lastAttemptAt].
     *
     * The sync worker calls this for each event returned in the Railway
     * `BatchUploadResponse.failed` list where `retryable == true`, and may also
     * call it for transient network errors. Callers set [retryIncrement] to 0
     * when recording a transient error without consuming a retry budget.
     *
     * Uses index: primary key lookup on `id` — O(1).
     *
     * @param id The [RawIngestionEventEntity.id] (UUID) of the failing event.
     * @param retryIncrement Amount to add to [RawIngestionEventEntity.retryCount].
     *   Defaults to 1. Pass 0 to update [lastAttemptAt] without incrementing.
     * @param now The wall-clock instant of the attempt, injected for testability.
     */
    @Query(
        """
        UPDATE raw_ingestion_events
        SET sync_status = 'failed',
            retry_count = retry_count + :retryIncrement,
            last_attempt_at = :now
        WHERE id = :id
        """,
    )
    public suspend fun markFailed(
        id: String,
        retryIncrement: Int = 1,
        now: Instant,
    )

    /**
     * Emits a live list of the most recent events associated with [personRef]
     * for [userId], ordered newest-first. Reacts to any write touching the
     * `raw_ingestion_events` table.
     *
     * Drives the PersonDetailScreen event timeline. The query is covered by
     * index `idx_raw_events_user_person_time` (user_id, person_ref, timestamp).
     *
     * @param userId The Supabase auth.users UUID.
     * @param personRef Canonicalized counterparty identifier (E.164 / email / name).
     * @param limit Maximum number of rows to emit per update.
     * @return Cold [Flow] that emits a new list on every relevant table write.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND person_ref = :personRef
        ORDER BY timestamp DESC
        LIMIT :limit
        """,
    )
    public fun observeRecentForPerson(
        userId: String,
        personRef: String,
        limit: Int,
    ): Flow<List<RawIngestionEventEntity>>

    /**
     * Emits a live list of the most recent events that have no identified
     * counterparty ([RawIngestionEventEntity.personRef] IS NULL) for [userId],
     * ordered newest-first. Drives the "Unassigned" group in the main timeline.
     *
     * Uses index: `idx_raw_events_user_time` (user_id, timestamp) — the NULL
     * filter on person_ref is applied as a residual predicate after the index
     * range scan on user_id.
     *
     * @param userId The Supabase auth.users UUID.
     * @param limit Maximum number of rows to emit per update.
     * @return Cold [Flow] that emits a new list on every relevant table write.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND person_ref IS NULL
        ORDER BY timestamp DESC
        LIMIT :limit
        """,
    )
    public fun observeUnassignedRecent(
        userId: String,
        limit: Int,
    ): Flow<List<RawIngestionEventEntity>>

    /**
     * Hard-deletes all events owned by [userId]. Called on logout to clear
     * local data per the local-first privacy model — data that has not yet been
     * synced is discarded without upload.
     *
     * @param userId The Supabase auth.users UUID.
     * @return The number of rows deleted.
     */
    @Query(
        """
        DELETE FROM raw_ingestion_events
        WHERE user_id = :userId
        """,
    )
    public suspend fun deleteAllForUser(userId: String): Int

    /**
     * Looks up a single event by its primary key [id], scoped to [userId].
     *
     * The user_id predicate prevents cross-user data leaks in multi-account or stale
     * back-stack scenarios: if one user's event UUID ends up in another user's navigation
     * arguments (e.g. process-death restore), this query returns null rather than the other
     * user's row. PK lookup stays O(1); the user_id check is a constant-time residual filter
     * on the fetched row.
     *
     * @param id The [RawIngestionEventEntity.id] UUID to look up.
     * @param userId The Supabase auth.users UUID of the owning user — enforces row-level scope.
     * @return The matching entity, or null if no row exists with this [id] for [userId].
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE id = :id
          AND user_id = :userId
        LIMIT 1
        """,
    )
    public suspend fun findById(id: String, userId: String): RawIngestionEventEntity?

    /**
     * Returns all voice events for [userId] that are blocked waiting for PIPA consent
     * ([RawIngestionEventEntity.syncStatus] = "awaiting_consent").
     *
     * Called when Stream 2 wires the consent toggle to determine how many events are queued.
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status).
     *
     * @param userId The Supabase auth.users UUID.
     * @return List of entities awaiting consent grant. May be empty.
     *
     * Spec refs: VOI-004.
     */
    @Query(
        "SELECT * FROM raw_ingestion_events " +
            "WHERE user_id = :userId " +
            "AND source_type = 'voice' " +
            "AND sync_status = 'awaiting_consent'",
    )
    public suspend fun findVoiceAwaitingConsent(userId: String): List<RawIngestionEventEntity>

    /**
     * Transitions all voice events for [userId] from "awaiting_consent" back to "pending"
     * so that [com.becalm.android.worker.VoiceUploadWorker] will pick them up on the next
     * enqueue triggered by the consent toggle going ON.
     *
     * Called by Stream 2 when PIPA third-party provision consent is granted.
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status).
     *
     * @param userId The Supabase auth.users UUID.
     * @return The number of rows updated (0 if no rows were waiting, ≥1 otherwise).
     *
     * Spec refs: VOI-004.
     */
    @Query(
        "UPDATE raw_ingestion_events " +
            "SET sync_status = 'pending' " +
            "WHERE user_id = :userId " +
            "AND source_type = 'voice' " +
            "AND sync_status = 'awaiting_consent'",
    )
    public suspend fun releaseAwaitingConsentVoice(userId: String): Int

    /**
     * Returns only the IDs (not full entities) of all voice events for [userId] that are
     * currently awaiting consent, keeping the payload small for the SELECT + UPDATE transaction.
     *
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status).
     *
     * @param userId The Supabase auth.users UUID.
     * @return List of [RawIngestionEventEntity.id] values for awaiting_consent voice rows.
     *
     * Spec refs: VOI-004.
     */
    @Query(
        "SELECT id FROM raw_ingestion_events " +
            "WHERE user_id = :userId " +
            "AND source_type = 'voice' " +
            "AND sync_status = 'awaiting_consent'",
    )
    public suspend fun findAwaitingConsentVoiceIds(userId: String): List<String>

    /**
     * Atomically transitions all voice events for [userId] from "awaiting_consent" to
     * "pending" and returns the IDs of the affected rows so the caller can re-enqueue
     * exactly those [com.becalm.android.worker.VoiceUploadWorker] jobs.
     *
     * The two-step SELECT + UPDATE runs inside a single [Transaction] so no concurrent
     * writer can insert a new awaiting_consent row that slips through without being
     * included in the returned ID list.
     *
     * Replaces the count-only [releaseAwaitingConsentVoice] for the consent-grant flow
     * in [com.becalm.android.ui.settings.SettingsViewModel] (finding #2 fix).
     *
     * @param userId The Supabase auth.users UUID.
     * @return The IDs that were released (empty when none were waiting).
     *
     * Spec refs: VOI-004.
     */
    @Transaction
    public suspend fun releaseAwaitingConsentVoiceAndReturnIds(userId: String): List<String> {
        val ids = findAwaitingConsentVoiceIds(userId)
        if (ids.isNotEmpty()) {
            releaseAwaitingConsentVoice(userId)
        }
        return ids
    }

    /**
     * Returns the IDs of all voice events for [userId] that are in a genuinely in-flight
     * state when consent is withdrawn — i.e. "pending", "queued", or "failed_retryable".
     *
     * "awaiting_consent" rows are intentionally excluded: they are already parked and have
     * no active WorkManager job to cancel. Including them caused spurious cancel calls and
     * re-parked the same rows unnecessarily (finding #1 re-review fix).
     *
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status).
     *
     * @param userId The Supabase auth.users UUID.
     * @return List of IDs for voice rows whose uploads should be cancelled and parked.
     *
     * Spec refs: VOI-004.
     */
    @Query(
        "SELECT id FROM raw_ingestion_events " +
            "WHERE user_id = :userId " +
            "AND source_type = 'voice' " +
            "AND sync_status IN ('pending', 'queued', 'failed_retryable')",
    )
    public suspend fun findCancellableVoiceIds(userId: String): List<String>

    /**
     * Parks voice events for [userId] that are in a genuinely in-flight state to
     * "awaiting_consent". Used when the user withdraws PIPA consent to freeze any
     * active voice uploads so they do not proceed after consent is revoked.
     *
     * Only transitions rows in "pending", "queued", or "failed_retryable" — already-parked
     * "awaiting_consent" rows and irreversible end states ("synced", "failed") are not touched.
     *
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status).
     *
     * @param userId The Supabase auth.users UUID.
     *
     * Spec refs: VOI-004.
     */
    @Query(
        "UPDATE raw_ingestion_events " +
            "SET sync_status = 'awaiting_consent' " +
            "WHERE user_id = :userId " +
            "AND source_type = 'voice' " +
            "AND sync_status IN ('pending', 'queued', 'failed_retryable')",
    )
    public suspend fun parkPendingVoiceToAwaitingConsent(userId: String)

    /**
     * Atomically selects the IDs of all voice events for [userId] in an in-flight state
     * ("pending", "queued", "failed_retryable"), then parks exactly those rows to "awaiting_consent".
     *
     * Running SELECT then UPDATE inside a single [Transaction] prevents a new "pending" row
     * inserted between the two statements from being parked without its ID being returned —
     * the exact race the two-call pattern in the repository had (finding #1 fix).
     *
     * @param userId The Supabase auth.users UUID.
     * @param now    Wall-clock epoch-millis stamped as `last_attempt_at` on parked rows.
     * @return The IDs that were parked (may be empty).
     *
     * Spec refs: VOI-004.
     */
    @Transaction
    public suspend fun parkCancellablePendingVoiceAndReturnIds(userId: String, now: Long): List<String> {
        val ids = findCancellableVoiceIds(userId)
        if (ids.isNotEmpty()) {
            parkVoiceByIds(ids, now)
        }
        return ids
    }

    /**
     * Parks the voice rows whose primary keys are in [ids] to "awaiting_consent".
     *
     * Only called from [parkCancellablePendingVoiceAndReturnIds]; private to that transaction.
     *
     * @param ids List of [RawIngestionEventEntity.id] values to park.
     * @param now Wall-clock epoch-millis to stamp as `last_attempt_at`.
     */
    @Query(
        "UPDATE raw_ingestion_events " +
            "SET sync_status = 'awaiting_consent', last_attempt_at = :now " +
            "WHERE id IN (:ids)",
    )
    public suspend fun parkVoiceByIds(ids: List<String>, now: Long)

    /**
     * Records a transient upload failure for a single voice event without changing
     * [RawIngestionEventEntity.syncStatus]. Increments [RawIngestionEventEntity.retryCount]
     * by 1 and records [now] as [RawIngestionEventEntity.lastAttemptAt].
     *
     * Called by [com.becalm.android.worker.VoiceUploadWorker.handleFailure] before
     * returning [androidx.work.ListenableWorker.Result.retry] so that retry metadata is
     * accumulated correctly across WorkManager attempts (VOI-006 finding #6 fix).
     *
     * Does **not** set sync_status to "failed" — the row stays "pending" so WorkManager
     * can retry it. Use [markFailed] with retryIncrement=0 for the final quarantine step.
     *
     * Uses index: primary key lookup on `id` — O(1).
     *
     * @param id The [RawIngestionEventEntity.id] UUID of the failing event.
     * @param now The wall-clock instant of the attempt, injected for testability.
     *
     * Spec refs: VOI-006.
     */
    @Query(
        """UPDATE raw_ingestion_events
           SET retry_count = retry_count + 1,
               last_attempt_at = :now
           WHERE id = :id""",
    )
    public suspend fun markTransientFailure(id: String, now: Instant)
}
