package com.becalm.android.data.local.db.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.becalm.android.data.local.db.entity.RawIngestionEventEntity
import kotlinx.coroutines.flow.Flow
import kotlinx.datetime.Instant

/**
 * Room DAO for [RawIngestionEventEntity].
 *
 * All queries that return data once are `suspend` functions executed on Room's
 * internal dispatcher. Observable queries return [Flow] and are collected by
 * the repository layer on the appropriate coroutine scope.
 *
 * Index usage is noted per query to aid future query-plan debugging:
 * - `idx_raw_events_user_sync`      → (user_id, sync_status)
 * - `idx_raw_events_user_time`      → (user_id, timestamp)
 * - `idx_raw_events_user_person_time` → (user_id, person_ref, timestamp)
 */
@Dao
public interface RawIngestionEventDao {

    /**
     * Inserts a single event. Uses [OnConflictStrategy.IGNORE] so that a duplicate
     * [RawIngestionEventEntity.clientEventId] (same idempotency key) is silently
     * dropped rather than throwing. The caller should check the returned row ID;
     * `-1L` means the row was ignored.
     *
     * @return The new row ID, or `-1L` if the row was ignored due to a conflict.
     */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    public suspend fun insert(entity: RawIngestionEventEntity): Long

    /**
     * Inserts a batch of events in a single transaction. Each item uses
     * [OnConflictStrategy.IGNORE] for the same idempotency guarantee as [insert].
     *
     * @return A list of row IDs parallel to [entities]; `-1L` at position N means
     *   the Nth entity was ignored due to a conflict.
     */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    public suspend fun insertAll(entities: List<RawIngestionEventEntity>): List<Long>

    /**
     * Replaces all columns of an existing row matched by primary key [RawIngestionEventEntity.id].
     *
     * @return The number of rows updated (0 if no matching row exists, 1 on success).
     */
    @Update
    public suspend fun update(entity: RawIngestionEventEntity): Int

    /**
     * Looks up an event by its client-generated idempotency key before inserting,
     * allowing callers to skip re-insertion entirely rather than relying solely on
     * the DB conflict strategy.
     *
     * Uses index: `idx_raw_events_user_sync` partial scan (user_id prefix) — full
     * coverage requires a composite index on (user_id, client_event_id), but the
     * idempotency check is low-frequency so the existing user_id index is sufficient.
     *
     * @param userId The Supabase auth.users UUID of the owning user.
     * @param clientEventId The UUID v4 idempotency key generated by the client.
     * @return The matching entity, or null if it does not yet exist locally.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND client_event_id = :clientEventId
        LIMIT 1
        """,
    )
    public suspend fun findByClientEventId(
        userId: String,
        clientEventId: String,
    ): RawIngestionEventEntity?

    /**
     * Returns up to [limit] events for [userId] whose [RawIngestionEventEntity.syncStatus]
     * is "pending", ordered oldest-first so that the sync worker uploads in ingestion order.
     *
     * Uses index: `idx_raw_events_user_sync` (user_id, sync_status) for the WHERE
     * predicate, then `idx_raw_events_user_time` (user_id, timestamp) for ORDER BY.
     *
     * @param userId The Supabase auth.users UUID.
     * @param limit Maximum number of rows to return (aligned to batch upload cap of 100).
     * @return List of pending entities, oldest timestamp first.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND sync_status = 'pending'
        ORDER BY timestamp ASC
        LIMIT :limit
        """,
    )
    public suspend fun findPendingForUpload(
        userId: String,
        limit: Int,
    ): List<RawIngestionEventEntity>

    /**
     * Marks a set of events as successfully synced by setting their
     * [RawIngestionEventEntity.syncStatus] to "synced" in a single UPDATE.
     *
     * Called by the sync worker after a successful Railway batch acknowledgement.
     * Room's `IN (:ids)` binding expands the list at compile time.
     *
     * @param ids List of [RawIngestionEventEntity.id] values to mark synced.
     */
    @Query(
        """
        UPDATE raw_ingestion_events
        SET sync_status = 'synced'
        WHERE id IN (:ids)
        """,
    )
    public suspend fun markSynced(ids: List<String>)

    /**
     * Records a failed upload attempt for a single event. Sets
     * [RawIngestionEventEntity.syncStatus] to "failed", increments
     * [RawIngestionEventEntity.retryCount] by [retryIncrement], and records
     * [now] as [RawIngestionEventEntity.lastAttemptAt].
     *
     * The sync worker calls this for each event returned in the Railway
     * `BatchUploadResponse.failed` list where `retryable == true`, and may also
     * call it for transient network errors. Callers set [retryIncrement] to 0
     * when recording a transient error without consuming a retry budget.
     *
     * Uses index: primary key lookup on `id` — O(1).
     *
     * @param id The [RawIngestionEventEntity.id] (UUID) of the failing event.
     * @param retryIncrement Amount to add to [RawIngestionEventEntity.retryCount].
     *   Defaults to 1. Pass 0 to update [lastAttemptAt] without incrementing.
     * @param now The wall-clock instant of the attempt, injected for testability.
     */
    @Query(
        """
        UPDATE raw_ingestion_events
        SET sync_status = 'failed',
            retry_count = retry_count + :retryIncrement,
            last_attempt_at = :now
        WHERE id = :id
        """,
    )
    public suspend fun markFailed(
        id: String,
        retryIncrement: Int = 1,
        now: Instant,
    )

    /**
     * Emits a live list of the most recent events associated with [personRef]
     * for [userId], ordered newest-first. Reacts to any write touching the
     * `raw_ingestion_events` table.
     *
     * Drives the PersonDetailScreen event timeline. The query is covered by
     * index `idx_raw_events_user_person_time` (user_id, person_ref, timestamp).
     *
     * @param userId The Supabase auth.users UUID.
     * @param personRef Canonicalized counterparty identifier (E.164 / email / name).
     * @param limit Maximum number of rows to emit per update.
     * @return Cold [Flow] that emits a new list on every relevant table write.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND person_ref = :personRef
        ORDER BY timestamp DESC
        LIMIT :limit
        """,
    )
    public fun observeRecentForPerson(
        userId: String,
        personRef: String,
        limit: Int,
    ): Flow<List<RawIngestionEventEntity>>

    /**
     * Emits a live list of the most recent events that have no identified
     * counterparty ([RawIngestionEventEntity.personRef] IS NULL) for [userId],
     * ordered newest-first. Drives the "Unassigned" group in the main timeline.
     *
     * Uses index: `idx_raw_events_user_time` (user_id, timestamp) — the NULL
     * filter on person_ref is applied as a residual predicate after the index
     * range scan on user_id.
     *
     * @param userId The Supabase auth.users UUID.
     * @param limit Maximum number of rows to emit per update.
     * @return Cold [Flow] that emits a new list on every relevant table write.
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE user_id = :userId
          AND person_ref IS NULL
        ORDER BY timestamp DESC
        LIMIT :limit
        """,
    )
    public fun observeUnassignedRecent(
        userId: String,
        limit: Int,
    ): Flow<List<RawIngestionEventEntity>>

    /**
     * Hard-deletes all events owned by [userId]. Called on logout to clear
     * local data per the local-first privacy model — data that has not yet been
     * synced is discarded without upload.
     *
     * @param userId The Supabase auth.users UUID.
     * @return The number of rows deleted.
     */
    @Query(
        """
        DELETE FROM raw_ingestion_events
        WHERE user_id = :userId
        """,
    )
    public suspend fun deleteAllForUser(userId: String): Int

    /**
     * Looks up a single event by its primary key [id].
     *
     * Added in SP-31 (VoiceTranscriptionWorker) to resolve a [RawIngestionEventEntity]
     * from the row UUID received as WorkManager input data, independent of user_id or
     * sync_status.
     *
     * Uses index: primary key lookup on `id` — O(1).
     *
     * @param id The [RawIngestionEventEntity.id] UUID to look up.
     * @return The matching entity, or null if no row exists with this [id].
     */
    @Query(
        """
        SELECT * FROM raw_ingestion_events
        WHERE id = :id
        LIMIT 1
        """,
    )
    public suspend fun findById(id: String): RawIngestionEventEntity?
}
